version: '3'
services:
  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    networks:
      - chat-net

  user-service:
    build:
      context: ./user-service
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - chat-net

networks:
  chat-net:
    driver: bridge
