apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbit-mq-pv
spec:
  storageClassName: "local-path"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/mnt/data"
  claimRef:
    namespace: real-time-chat-app
    name: rabbit-mq-pvc
