apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql
  namespace: real-time-chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql
  template:
    metadata:
      labels:
        app: graphql
    spec:
      containers:
      - name: graphql
        image: grejs420/graphql:main
        ports:
        - containerPort: 4000
        - containerPort: 4001  # Added port for health check service
        envFrom:
        - configMapRef:
            name: real-time-chat-config
        - secretRef:
            name: real-time-chat-secrets
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 4001  # Use health check service port
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 4001  # Use health check service port
          initialDelaySeconds: 30
          periodSeconds: 10
