apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql
  namespace: real-time-chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql
  template:
    metadata:
      labels:
        app: graphql
    spec:
      containers:
      - name: graphql
        image: grejs420/graphql:main
        ports:
        - containerPort: 4000
        envFrom:
        - configMapRef:
            name: real-time-chat-config
        - secretRef:
            name: real-time-chat-secrets
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
