apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: real-time-chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: grejs420/user-service:main
        ports:
        - containerPort: 3001
        envFrom:
        - configMapRef:
            name: real-time-chat-config
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: real-time-chat-secrets
              key: JWT_SECRET
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: real-time-chat-secrets
              key: RABBITMQ_DEFAULT_USER
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: real-time-chat-secrets
              key: RABBITMQ_DEFAULT_PASS
        - name: RABBITMQ_URL
          value: "amqp://$(RABBITMQ_DEFAULT_USER):$(RABBITMQ_DEFAULT_PASS)@$(RABBITMQ_HOST):$(RABBITMQ_PORT)"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3001
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
