apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: real-time-chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: grejs420/chat-service:latest
          ports:
            - containerPort: 3001
          env:
            - name: BASE_URL
              value: "/swwao.courses.orbit.au.dk/grp-6/chat"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: JWT_SECRET
            - name: GRAPHQL_URI
              value: "http://graphql-gateway:4000/graphql"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"