apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: real-time-chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
      - name: chat-service
        image: grejs420/chat-service:latest
        ports:
        - containerPort: 3002
        envFrom:
        - configMapRef:
            name: real-time-chat-config
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: real-time-chat-secrets
              key: JWT_SECRET
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: real-time-chat-secrets
              key: RABBITMQ_DEFAULT_USER
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: real-time-chat-secrets
              key: RABBITMQ_DEFAULT_PASS
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
