apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: real-time-chat-app
spec:
  selector:
    app: chat-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
