apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-volume-pvc
  namespace: real-time-chat-app
spec:
  storageClassName: "local-path"  
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
