apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-gateway
  namespace: real-time-chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql-gateway
  template:
    metadata:
      labels:
        app: graphql-gateway
    spec:
      containers:
      - name: graphql-gateway
        image: grejs420/graphql-gateway:latest
        ports:
        - containerPort: 4000
        env:
        - name: MONGODB_URI
          value: "mongodb://mongo:27017/userdb"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-service-secrets
              key: JWT_SECRET
        - name: RABBITMQ_URL
          value: "amqp://user:password@rabbitmq:5672"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
