apiVersion: v1
kind: Service
metadata:
  name: graphql-gateway
  namespace: real-time-chat-app
spec:
  selector:
    app: graphql-gateway
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP