apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service
  namespace: real-time-chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-service
  template:
    metadata:
      labels:
        app: message-service
    spec:
      containers:
      - name: message-service
        image: grejs420/message-service:main
        ports:
        - containerPort: 3003
        envFrom:
        - configMapRef:
            name: real-time-chat-config
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: real-time-chat-secrets
              key: JWT_SECRET
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: real-time-chat-secrets
              key: RABBITMQ_DEFAULT_USER
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: real-time-chat-secrets
              key: RABBITMQ_DEFAULT_PASS
        - name: RABBITMQ_URL
          value: "amqp://$(RABBITMQ_DEFAULT_USER):$(RABBITMQ_DEFAULT_PASS)@$(RABBITMQ_HOST):$(RABBITMQ_PORT)"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
