apiVersion: v1
kind: Service
metadata:
  name: message-service
  namespace: real-time-chat-app
spec:
  selector:
    app: message-service
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
