apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: real-time-chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: grejs420/auth-service:latest
        ports:
        - containerPort: 3000
        env:
        - name: BASE_URL
          value: "/swwao.courses.orbit.au.dk/grp-6/auth"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-service-secrets
              key: JWT_SECRET
        - name: GRAPHQL_URI
          value: "http://graphql-gateway:4000/graphql"
        - name: RABBITMQ_URL
          value: "amqp://user:password@rabbitmq:5672"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
