apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: real-time-chat-app
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP