apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-volume-pv
spec:
  storageClassName: "local-path"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/data/dbmongo"
  claimRef:
    namespace: real-time-chat-app
    name: mongo-volume-pvc

